# Generated by Django 5.0.6 on 2024-07-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_fooditem_remove_fooditems_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'fooditems',
            },
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='user',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
