# Generated by Django 5.0.6 on 2024-07-05 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_fooditems_remove_consumption_food_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=50)),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories.fooditems')),
            ],
            options={
                'db_table': 'usertable',
            },
        ),
    ]
