# Generated by Django 5.0.6 on 2024-07-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_alter_userentry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='fooditem',
            field=models.CharField(max_length=50),
        ),
    ]
