# Generated by Django 5.0.6 on 2024-07-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0006_alter_userentry_fooditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentry',
            old_name='fooditem',
            new_name='ufood',
        ),
    ]
