# Generated by Django 5.0.6 on 2024-07-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0007_rename_fooditem_userentry_ufood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentry',
            old_name='ufood',
            new_name='food_by_user',
        ),
    ]
