# Generated by Django 5.0.6 on 2024-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0008_rename_ufood_userentry_food_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='food_by_user',
        ),
        migrations.AddField(
            model_name='userentry',
            name='food_by_user',
            field=models.ManyToManyField(to='calories.fooditems'),
        ),
    ]
