# Generated by Django 5.0.6 on 2024-07-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0009_remove_userentry_food_by_user_userentry_food_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='user_name',
        ),
    ]
