# Generated by Django 5.0.6 on 2024-07-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0010_remove_userentry_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='user_name',
            field=models.CharField(default='name of food', max_length=100),
        ),
    ]
