# Generated by Django 5.0.6 on 2024-07-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0011_userentry_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
