# Generated by Django 5.0.6 on 2024-07-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0012_alter_userentry_quantity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userentry',
            table='UserData',
        ),
    ]
