# Generated by Django 5.0.6 on 2024-07-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0013_alter_userentry_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userEntry',
            new_name='UserData',
        ),
        migrations.AlterModelTable(
            name='userdata',
            table='UserInfo',
        ),
    ]
