# Generated by Django 4.2.13 on 2024-07-09 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0014_rename_userentry_userdata_alter_userdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AddField(
            model_name='consume',
            name='food_consumed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories.fooditems'),
        ),
        migrations.AddField(
            model_name='consume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
