# Generated by Django 4.2.13 on 2024-07-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0015_consume_remove_fooditems_quantity_delete_userdata_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consume',
            table='calories_consume',
        ),
    ]
